# Generated by Django 5.2.7 on 2025-11-17 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_remove_appointment_notes_remove_professional_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.professional', verbose_name='Profesional'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre:'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Eléctronico'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='first_name',
            field=models.CharField(max_length=80, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='last_name',
            field=models.CharField(max_length=80, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='profession',
            field=models.CharField(choices=[('Matemática', 'Profesor de Matemática'), ('Lenguaje', 'Profesor de Lenguaje'), ('Domicilio', 'Educadora Diferencial Domicilio'), ('IT', 'Consultor IT')], max_length=50, verbose_name='Profesional'),
        ),
    ]
